spring.application.name=java_condominio

spring.datasource.url=jdbc:postgresql://localhost:5432/java_condominio
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update