-- Table: public.imovel

-- DROP TABLE IF EXISTS public.imovel;

CREATE TABLE IF NOT EXISTS public.imovel
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    bloco character varying(255) COLLATE pg_catalog."default",
    apartamento character varying(255) COLLATE pg_catalog."default",
    box_garagem character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT imovel_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.imovel
    OWNER to postgres;