-- Table: public.morador

-- DROP TABLE IF EXISTS public.morador;

CREATE TABLE IF NOT EXISTS public.morador
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nome character varying(255) COLLATE pg_catalog."default",
	celular character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
	is_proprietario boolean,
    data_entrada timestamp without time zone,
	data_saida timestamp without time zone,
    data_inclusao timestamp without time zone NOT NULL,
	data_alteracao timestamp without time zone,
    imovel_id bigint NOT NULL,
    CONSTRAINT morador_pkey PRIMARY KEY (id),
    CONSTRAINT fkfpqrgyjux3g8yyj49fgq6e88 FOREIGN KEY (imovel_id)
        REFERENCES public.imovel (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.morador
    OWNER to postgres;